#!/usr/bin/env python3

from .context import PyGeneology
from PyGeneology import pygenelib as pglib

# Using the Weasleys as a test case:
# https://s-media-cache-ak0.pinimg.com/originals/3a/00/fe/3a00fe23b37c9e325666ae0923c0deb1.jpg
harry = pglib.Person(pglib.male, first="Harry", middle="James", last="Potter")
lily = pglib.Person(pglib.female, first="Lily", last="Potter", unmarried_name="Evans", child=harry)
james = pglib.Person(pglib.male, first="James", last="Potter", child=harry, spouse=lily)
ginny = pglib.Person(pglib.female, first="Ginny", last="Potter", unmarried_name="Weasley", spouse=harry)
ron = pglib.Person(pglib.male, first="Ronald", middle="Bilius", last="Granger-Weasley",
                   unmarried_name="Weasley")
hermione = pglib.Person(pglib.female, first="Hermione", middle="Jean", last="Granger-Weasley",
                        unmarried_name="Granger", spouse=ron)
arthur = pglib.Person(pglib.male, first="Arthur", last="Weasley", child=ron)
molly = pglib.Person(pglib.female, first="Molly", last="Weasley", unmarried_name="Prewett",
                     spouse=arthur, child=ron)
ginny.add_parent(arthur)
ginny.add_parent(molly)
bill = pglib.Person(pglib.male, first="William", last="Weasley", parent=arthur)
bill.add_parent(molly)
fleur = pglib.Person(pglib.female, first="Fleur", last="Delcour", spouse=bill)
charlie = pglib.Person(pglib.male, first="Charlie", last="Weasley", parent=arthur)
charlie.add_parent(molly)
percy = pglib.Person(pglib.male, first="Percy", last="Weasley", parent=arthur)
percy.add_parent(molly)
audrey = pglib.Person(pglib.female, first="Audrey", last="Weasley", spouse=percy)
fred = pglib.Person(pglib.male, first="Fred", last="Weasley", parent=arthur)
fred.add_parent(molly)
george = pglib.Person(pglib.male, first="George", last="Weasley", parent=arthur)
george.add_parent(molly)
angelina = pglib.Person(pglib.female, first="Angelina", last="Johnson", spouse=george)

jp2 = pglib.Person(pglib.male, first="James", last="Potter", suffix="II", parent=harry)
jp2.add_parent(ginny)
albus = pglib.Person(pglib.male, first="Albus", middle="Severus", last="Potter", parent=harry)
albus.add_parent(ginny)
lp2 = pglib.Person(pglib.female, first="Lily", last="Potter", suffix="II", parent=harry)
lp2.add_parent(ginny)

hugo = pglib.Person(pglib.male, first="Hugo", last="Granger-Weasley", parent=ron)
hugo.add_parent(hermione)
rose = pglib.Person(pglib.female, first="Rose", last="Granger-Weasley", parent=ron)
rose.add_parent(hermione)

fw2 = pglib.Person(pglib.male, first="Fred", last="Weasley", parent=george)
fw2.add_parent(angelina)
roxanne = pglib.Person(pglib.female, first="Roxanne", last="Weasley", parent=george)
roxanne.add_parent(angelina)

lucy = pglib.Person(pglib.female, first="Lucy", last="Weasley", parent=percy)
lucy.add_parent(audrey)
mw2 = pglib.Person(pglib.female, first="Molly", last="Weasley", parent=percy)
mw2.add_parent(audrey)

victoire = pglib.Person(pglib.female, first="Victoire", last="Weasley", parent=bill)
victoire.add_parent(fleur)
dominique = pglib.Person(pglib.female, first="Dominique", last="Weasley", parent=bill)
dominique.add_parent(fleur)
louis = pglib.Person(pglib.male, first="Louis", last="Weasley", parent=bill)
louis.add_parent(fleur)

teddy = pglib.Person(pglib.male, first="Theodore", last="Lupin", spouse=victoire)
remus = pglib.Person(pglib.male, first="Remus", last="Lupin", child=teddy)
dora = pglib.Person(pglib.female, first="Nymphadora", last="Tonks", child=teddy, spouse=remus)

weasleys = pglib.Family()
weasleys.add_member(harry)
weasleys.add_member(lily)
weasleys.add_member(james)
weasleys.add_member(ginny)
weasleys.add_member(ron)
weasleys.add_member(hermione)
weasleys.add_member(arthur)
weasleys.add_member(molly)
weasleys.add_member(bill)
weasleys.add_member(fleur)
weasleys.add_member(charlie)
weasleys.add_member(percy)
weasleys.add_member(audrey)
weasleys.add_member(fred)
weasleys.add_member(george)
weasleys.add_member(angelina)

weasleys.add_member(jp2)
weasleys.add_member(albus)
weasleys.add_member(lp2)
weasleys.add_member(hugo)
weasleys.add_member(rose)
weasleys.add_member(fw2)
weasleys.add_member(roxanne)
weasleys.add_member(lucy)
weasleys.add_member(mw2)
weasleys.add_member(victoire)
weasleys.add_member(dominique)
weasleys.add_member(louis)
weasleys.add_member(teddy)
weasleys.add_member(remus)
weasleys.add_member(dora)